apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-demo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/GhaithDhaouadi/platform-gitops-lab.git
    targetRevision: main
    path: apps/otel-demo/base
  destination:
    server: https://kubernetes.default.svc
    namespace: otel-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
